import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { Headphones } from 'lucide';
await build({ entryPoints: ['frontend/app.js'], outfile: 'web/app.js', bundle: true, format: 'esm', minify: true, target: 'es2022', legalComments: 'eof' });
await build({ entryPoints: ['frontend/portal.js'], outfile: 'web/portal.js', bundle: true, format: 'esm', minify: true, target: 'es2022', legalComments: 'eof' });
await build({ entryPoints: ['frontend/admin-login.js'], outfile: 'web/admin-login.js', bundle: true, format: 'esm', minify: true, target: 'es2022', legalComments: 'eof' });
const paths = Headphones.map(([tag, attributes]) => `<${tag} ${Object.entries(attributes).map(([key, value]) => `${key}="${value}"`).join(' ')}/>`).join('');
await writeFile('web/favicon.svg', `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#477968" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${paths}</svg>`);
const hash = createHash('sha256');
for (const file of ['app.js', 'portal.js', 'admin-login.js', 'admin.css', 'rooms.css', 'style.css', 'theme.css', 'favicon.svg']) hash.update(await readFile(`web/${file}`));
const revision = hash.digest('hex').slice(0, 12);
const html = await readFile('web/index.html', 'utf8');
await writeFile('web/index.html', html.replace(/((?:href|src)="\/(?:app\.js|style\.css|theme\.css|favicon\.svg))(?:\?v=[^"]*)?"/g, `$1?v=${revision}"`));
const roomsHtml = await readFile('web/rooms.html', 'utf8');
await writeFile('web/rooms.html', roomsHtml.replace(/((?:href|src)="\/(?:portal\.js|rooms\.css|favicon\.svg))(?:\?v=[^"]*)?"/g, `$1?v=${revision}"`));
const adminHtml = await readFile('web/admin.html', 'utf8');
await writeFile('web/admin.html', adminHtml.replace(/((?:href|src)="\/(?:admin-login\.js|admin\.css|rooms\.css|favicon\.svg))(?:\?v=[^"]*)?"/g, `$1?v=${revision}"`));
console.log('Web console bundle built.');
